[package]
name = "gostrafx/Rojo"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.7"
Component = "sleitnick/component@2.4.8"
EnumList = "sleitnick/enum-list@2.1.0"
Input = "sleitnick/input@2.3.0"
Streamable = "sleitnick/streamable@1.2.4"
Symbol = "sleitnick/symbol@2.0.1"
Quaternion = "sleitnick/quaternion@0.2.3"
Shake = "sleitnick/shake@1.1.0"
TableUtil = "sleitnick/table-util@1.2.1"
Timer = "sleitnick/timer@1.1.2"
Trove = "sleitnick/trove@1.5.0"
WaitFor = "sleitnick/wait-for@1.0.0"
Tree = "sleitnick/tree@1.1.0"
TaskQueue = "sleitnick/task-queue@1.0.0"
Silo = "sleitnick/silo@0.2.0"
Comm = "sleitnick/comm@1.0.1"
Component = "sleitnick/component@2.4.8"
Option = "sleitnick/option@1.0.5"	
Signal = "sleitnick/signal@2.0.3"	
promise = "evaera/promise@4.0.0"